#!/usr/bin/env zsh

set -ux

if ! git remote show grimreaper > /dev/null 2>&1
then
  echo "remote with name grimreaper must exist"
  exit 1
fi

if [ $# -ne 3 ]
then
  echo "$0: midname tip base"
  exit 1
fi

today=$(date "+%Y-%m-%d")
export GIT_COMMITTER_DATE="${today}T12:00:00-07:00"
export GIT_AUTHOR_DATE="${today}T12:00:00-07:00"

MIDNAME="$1"
NEW="$2"
BASE="$3"
for sha in $(git log --format="%h" $(git merge-base "$NEW" "$BASE" ).."$NEW");
do
  git checkout -b eax/$MIDNAME/$sha origin/master && (git cherry-pick "$sha"|| git cherry-pick --abort);
done;
git push --mirror grimreaper
git push --mirror grimreaper
for ref in $(git for-each-ref --format="%(refname)" "refs/heads/eax/$MIDNAME/")
do
  ref="${ref##refs/heads/}"
  hub pull-request -h "$ref" -m "$(git log --no-walk --format=%s $ref)"
done
git checkout master
git clean-branches
