#!/usr/bin/env zsh

ccache_pattern="(cache directory|cleanups|cache size)"

print -nP "%F{blue}poudriere ccache stats%f\n" 2>&1 
env CCACHE_DIR=/srv/obj/ccache-poudriere ccache -s | grep -E "$ccache_pattern"
print -nP "%F{blue}local ccache stats%f\n"
ccache -s 2>&1 | grep -E "$ccache_pattern"

print -nP "%F{blue}Boot Information%f\n"
sysctl kern.bootfile

