#!/usr/bin/env zsh

title() {
  print -nP "%F{blue}$@%f\n"
}

ccache_pattern="(cache directory|cleanups|cache size|cache hit rate)"

title "poudriere ccache stats"
env CCACHE_DIR=/srv/obj/ccache-poudriere ccache -s | grep -E "$ccache_pattern"
title "local ccache stats"
ccache -s 2>&1 | grep -E "$ccache_pattern"

title "Boot Information"
sysctl kern.bootfile
cur_be="$(beadm list -H|awk '$2 ~ /N/ {print $1}')"
next_be="$(beadm list -H|awk '$2 ~ /R/ {print $1}')"
printf "boot env: %s\n" "$cur_be"
if [[ "$cur_be" != "$next_be" ]]
then
  print -nP "boot env reboot: %B$next_be%b\n"
fi

title "sysctl tuning"
float cur_vnodes="$(sysctl -n vfs.numvnodes)"
float max_vnodes="$(sysctl -n kern.maxvnodes)"

printf "numnodes usage: %0.2f%%\n" $(( $cur_vnodes / $max_vnodes ))
