#!/bin/sh
# Github
git config --add remote.origin.fetch '+refs/pull/*/head:refs/remotes/origin/pr/*'

# Stash
git config --add remote.origin.fetch '+refs/pull-requests/*/from:refs/remotes/origin/pr/*'
