---
https://wttr.in:
  decr: weather report
  method: [curl]
  tags: [weather]
https://wttr.in/Moon:
  descr: moon phase
  method: [curl]
  tags: [weather]
https://rate.sx:
  descr: cryptocoin exchange rate
  method: [curl]
https://ipaddress.sh:
  descr: current ip
  method: [curl]
  tags: [currentip]
https://checkip.amazonaws.com:
  descr: current ip
  method: [curl]
  tags: [currentip]
https://ifconfig.in:
  descr: current ip
  method: [curl]
  tags: [currentip]
https://ifconfig.co/[format]:
  descr: current ip and associated data
  method: [curl]
  tags: [currentip]
  patterns:
      format: text, xml, json
https://wtfismyip.com/[format]:
  descr: current ip and associated data
  method: [curl]
  tags: [currentip]
  patterns:
      format: text, xml, json
https://ipecho.net/[format]:
  descr: current ip and associated data
  method: [curl]
  tags: [currentip]
  patterns:
      format: text, xml, json
https:/ppoptart.spinda.net:
  descr: poptart cat
  method: [curl]
mapscii.me:
  descr: maps
  method: [telnet]
rainmaker.wunderground.com:3000:
  descr: weather
  method: [telnet]
  tags: [weather]
nyancat.dakko.us:
  descr: nyancat
  method: [telnet]
india.colorado.edu:13:
  descr: time
  method: [telnet]
telnet.wmflabs.org:
  descr: telnet gateway to wikimedia content (more info)
  method: [telnet]
telehack.com:
  descr: Telehack
  method: [web, telnet]
freechess.org  5000:
  descr: freechess.org
  method: [telnet]
towel.blinkenlights.nl:
  descr: Star Wars asciimation
  method: [telnet]
towel.blinkenlights.nl:666:
  descr: The Bofh Excuse Server
  method: [telnet]
mtrek.com:1701:
  descr: mtrek (star trek themed game)
  method: [telnet]
xmltrek.com:1701:
  descr: xmltrek (star trek themed game)
  method: [telnet]
telehack.com:
  descr: old unix server
  method: [telnet]
freechess.org:
  descr: chess
  method: [telnet]
  tags: [games]
rya.nc:1987:
  descr: disco
  method: [telnet]
milek7.gq:
  descr: games (Pong, Breakout, tetris)
  method: [telnet]
  tags: [games]
pacman:pacman@antimirov.net:
  descr: pacman
  method: [ssh]
  tags: [games]
https://cheat.sh/[command]:
  descr: get information about unix commands
  method: [curl]
  patterns:
      command: unix command
http://parrot.live:
  descr: party parrot!
  method: [curl]
"myip.opendns.com @resolver1.opendns.com":
  descr: print current IP address
  method: [dns]
  tags: [currentip]
https://api.ipify.org:
  descr: print current IP address
  method: [curl]
  tags: [currentip]
"dig TXT +short o-o.myaddr.l.google.com":
  descr: print current IP address
  method: [exec]
  tags: [currentip]
"dig TXT +short -6 @ns1.google.com o-o.myaddr.l.google.com":
  descr: print current IP address
  method: [exec]
  tags: [currentip]
"curl dict://dict.org/d:[word]":
  descr: defines words
  method: [exec]
